server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
      - id: customerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/customer/**
      - id: productModule
        uri: http://localhost:8083/
        predicates:
        - Path=/product/**
      - id: loginModule
        uri: http://localhost:8084/
        predicates:
        - Path=/login/**